Controllers/LocationController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using GMB.Models;
using System.Web.Http;
using System.Net;
using System.Net.Http;
using Newtonsoft.Json;
using RestSharp;
using System.Text;
using Microsoft.AspNetCore.Http;

namespace GMB.Controllers
{
    public class LocationController : Controller
    {
        private readonly ILogger<LocationController> _logger;

        public LocationController(ILogger<LocationController> logger)
        {
            _logger = logger;
        }

        public IActionResult List(string accountName)
        {
            var locations = GetLocationsForAccount(accountName);
            return View(locations);
        }

        public LocationsModel GetLocationsForAccount(string accountName)
        {
            var bearerToken = HttpContext.Session.GetString("Access_Token");
            var client = new RestClient($"https://mybusiness.googleapis.com/v4/{accountName}/locations");
            client.Timeout = -1;
            client.AddDefaultHeader("Authorization", string.Format("Bearer {0}", bearerToken));
            var request = new RestRequest(Method.GET);
            IRestResponse response = client.Execute(request);

            return JsonConvert.DeserializeObject<LocationsModel>(response.Content);
        }

        [Microsoft.AspNetCore.Mvc.HttpPost]
        public IActionResult UpdateLocation(Location location)
        {
            var bearerToken = HttpContext.Session.GetString("Access_Token");
            var client = new RestClient($"https://mybusiness.googleapis.com/v4/{location.name}");
            client.Timeout = -1;
            client.AddDefaultHeader("Authorization", string.Format("Bearer {0}", bearerToken));
            var request = new RestRequest(Method.PATCH);
            request.AddParameter("updateMask", "primaryPhone");
            request.AddJsonBody(JsonConvert.SerializeObject(location));
            IRestResponse response = client.Execute(request);

            return View("");
        }
    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - GMB</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">GMB</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Account" asp-action="AccountList">Accounts</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - GMB - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

Views/Shared/_Location.cshtml
@model Location

@using (Html.BeginForm("UpdateLocation", "Location", FormMethod.Post,
                    new { enctype = "multipart/form-data" }))
{
    @Html.HiddenFor(x => x.name)
    @Html.HiddenFor(x => x.locationName)
    @Html.HiddenFor(x => x.languageCode)
    <fieldset>
        <legend>@Model.locationName</legend>

        @Html.TextBoxFor(x => x.primaryPhone)

        @Html.TextBoxFor(x => x.websiteUrl)
        <fieldset>
            <legend>Category</legend>
            @Html.TextBoxFor(x => x.primaryCategory.displayName)
            @Html.TextBoxFor(x => x.primaryCategory.categoryId)
        </fieldset>

        <fieldset>
            <legend>ServiceArea</legend>
            @Html.TextBoxFor(x => x.serviceArea.businessType)

            @*@Html.EditorFor(x => x.serviceArea.places.placeInfos)*@

            @for (int i = 0; i < Model.serviceArea.places.placeInfos.Count; i++)
            {
                @Html.HiddenFor(x => x.serviceArea.places.placeInfos[i].name)
                @Html.HiddenFor(x => x.serviceArea.places.placeInfos[i].placeId)
            }
        </fieldset>

        <fieldset>
            <legend>LocationKey</legend>
            @Html.TextBoxFor(x => x.locationKey.placeId)
            @Html.TextBoxFor(x => x.locationKey.requestId)
        </fieldset>

        <fieldset>
            <legend>Open Info</legend>
            @Html.TextBoxFor(x => x.openInfo.canReopen)
            @Html.TextBoxFor(x => x.openInfo.status)
        </fieldset>

        <fieldset>
            <legend>Address</legend>
            @Html.EditorFor(x => x.address.addressLines)
            @Html.TextBoxFor(x => x.address.locality)
            @Html.TextBoxFor(x => x.address.postalCode)
            @Html.TextBoxFor(x => x.address.regionCode)
        </fieldset>
    </fieldset>

    <button class="location-submit" type="submit">Submit location</button>
}